var SW = {
    Canvas: null,
    Collection: null,
    Config: null,
    Dom: null,
    Draw: null,
    FSM: null,
    Game: null,
    Input: null,
    Loading: null,
    MediaManager: null,
    Rectangle: null,
    Renderable: null,
    Sprite: null,
    State: null,
};