export default {
    altKey: false,
    bubbles: true,
    button: 0,
    buttons: 0,
    cancelBubble: false,
    cancelable: true,
    clientX: 32,
    clientY: 32,
    composed: true,
    ctrlKey: false,
    currentTarget: null,
    defaultPrevented: false,
    detail: 1,
    eventPhase: 0,
    fromElement: null,
    isTrusted: true,
    layerX: 32,
    layerY: 32,
    metaKey: false,
    movementX: 0,
    movementY: 0,
    offsetX: 32,
    offsetY: 32,
    pageX: 32,
    pageY: 32,
    path: [],
    relatedTarget: null,
    returnValue: true,
    screenX: 32,
    screenY: 32,
    shiftKey: false,
    sourceCapabilities: {},
    srcElement: null,
    target: null,
    timeStamp: 1127768.25,
    toElement: null,
    type: "click",
    view: null,
    which: 1,
    x: 32,
    y: 32,
    preventDefault () {},
    stopPropagation () {},
    stopImmediatePropagation () {}
};
